name = "hugo-ganzi"
description = "WordPress weisaybox/weisaygrace theme for Hugo"
homepage = "https://blog.zznuo.com"
tags = ["blog", "personal"]
features = ["dark mode", "random thumbnails"]

[author]
  name = "ganzi"
  homepage = "https://blog.zznuo.com"
